# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

target 'VK App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherApp737
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'Kingfisher', '~> 6.0.1'
  pod 'RealmSwift'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'PromiseKit'
  pod 'PromiseKit/Alamofire'

end
