# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VK App' do

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VK App
  pod 'Alamofire', '~> 5.2'

  target 'VK AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VK AppUITests' do
    # Pods for testing
  end

end
