# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NyaWeather (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NyaWeather (iOS)

  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Kingfisher'
  pod 'RealmSwift'
  #pod 'ObjectMapper'
  pod 'AlamofireObjectMapper', '~> 6.1.0'

end

target 'NyaWeather (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NyaWeather (macOS)

end
